// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBW8L8u5ENzheeEMl_59ClrhbB0JF3Q28',
    appId: '1:1048336534814:web:56e8cf1838315590194d0f',
    messagingSenderId: '1048336534814',
    projectId: 'wsuroutes-9d442',
    authDomain: 'wsuroutes-9d442.firebaseapp.com',
    storageBucket: 'wsuroutes-9d442.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0BNLgDf6CbjIPiMlWN8DmTpnT8PgjDM',
    appId: '1:1048336534814:android:6ebd447c74eea792194d0f',
    messagingSenderId: '1048336534814',
    projectId: 'wsuroutes-9d442',
    storageBucket: 'wsuroutes-9d442.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyr293Xyxm_umm7mYzwen2n35SUpa3qVI',
    appId: '1:1048336534814:ios:9b8c869e475f3009194d0f',
    messagingSenderId: '1048336534814',
    projectId: 'wsuroutes-9d442',
    storageBucket: 'wsuroutes-9d442.firebasestorage.app',
    iosBundleId: 'com.example.googleMapsInFlutter',
  );
}
