name: Flutter CI
# sets up the runner
run-name: WSU_Routes testing workflow.
on:
  push:
    branches: [ "main", "actions_test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: setup backend server
        working-directory: WSU_ROUTES_API
        run: python -m venv venv
      
      - name: install dependencies 
        working-directory: WSU_ROUTES_API
        run: pip install -r requirements.txt
      # starts a server but never exits CI isnt the right place to run a live server
      # - name: run python backend server
      #   working-directory: WSU_ROUTES_API
      #   run: python app.py

      - name: Install flutter dependencies
        working-directory: google_maps_in_flutter
        run: flutter pub get

      - name: Analyze project source
        working-directory: google_maps_in_flutter
        run: flutter analyze

      - name: Run tests
        working-directory: google_maps_in_flutter
        run: flutter test
